version: '3.8'

services:
  postgres:
    image: postgres:16.3
    container_name: postgres-dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env.dev  # Loads environment variables
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: